!function(e){var n={};function r(t){if(n[t])return n[t].exports;var o=n[t]={i:t,l:!1,exports:{}};return e[t].call(o.exports,o,o.exports,r),o.l=!0,o.exports}r.m=e,r.c=n,r.d=function(e,n,t){r.o(e,n)||Object.defineProperty(e,n,{enumerable:!0,get:t})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,n){if(1&n&&(e=r(e)),8&n)return e;if(4&n&&"object"==typeof e&&e&&e.__esModule)return e;var t=Object.create(null);if(r.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:e}),2&n&&"string"!=typeof e)for(var o in e)r.d(t,o,function(n){return e[n]}.bind(null,o));return t},r.n=function(e){var n=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(n,"a",n),n},r.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},r.p="",r(r.s="./src/js/aspirant.js")}({"./src/js/aspirant.js":
/*!****************************!*\
  !*** ./src/js/aspirant.js ***!
  \****************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _modal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./modal */ \"./src/js/modal.js\");\n/* harmony import */ var _modal__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(_modal__WEBPACK_IMPORTED_MODULE_0__);\nfunction _toConsumableArray(arr) { return _arrayWithoutHoles(arr) || _iterableToArray(arr) || _unsupportedIterableToArray(arr) || _nonIterableSpread(); }\n\nfunction _nonIterableSpread() { throw new TypeError(\"Invalid attempt to spread non-iterable instance.\\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.\"); }\n\nfunction _unsupportedIterableToArray(o, minLen) { if (!o) return; if (typeof o === \"string\") return _arrayLikeToArray(o, minLen); var n = Object.prototype.toString.call(o).slice(8, -1); if (n === \"Object\" && o.constructor) n = o.constructor.name; if (n === \"Map\" || n === \"Set\") return Array.from(o); if (n === \"Arguments\" || /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n)) return _arrayLikeToArray(o, minLen); }\n\nfunction _iterableToArray(iter) { if (typeof Symbol !== \"undefined\" && Symbol.iterator in Object(iter)) return Array.from(iter); }\n\nfunction _arrayWithoutHoles(arr) { if (Array.isArray(arr)) return _arrayLikeToArray(arr); }\n\nfunction _arrayLikeToArray(arr, len) { if (len == null || len > arr.length) len = arr.length; for (var i = 0, arr2 = new Array(len); i < len; i++) { arr2[i] = arr[i]; } return arr2; }\n\n///modal\n ///\n/// gifs\n\nvar gifs = _toConsumableArray(document.querySelectorAll('.aspirant-info__titles > img'));\n\nvar titles = _toConsumableArray(document.querySelectorAll('.aspirant-info__titles > h3'));\n\nvar _loop = function _loop(i) {\n  titles[i].addEventListener('mouseenter', function () {\n    titles[i].classList.toggle('active');\n    gifs[i].classList.toggle('active');\n  });\n  titles[i].addEventListener('mouseleave', function () {\n    titles[i].classList.toggle('active');\n    gifs[i].classList.toggle('active');\n  });\n};\n\nfor (var i = 0; i < titles.length; i++) {\n  _loop(i);\n} /// gifs end\n\n//# sourceURL=webpack:///./src/js/aspirant.js?")},"./src/js/modal.js":
/*!*************************!*\
  !*** ./src/js/modal.js ***!
  \*************************/
/*! no static exports found */function(module,exports){eval("var modal = document.querySelector('.modal');\nvar overlay = document.querySelector('.overlay');\n\nvar close = function close() {\n  document.body.style.overflow = 'initial';\n  modal.style.opacity = 0;\n  overlay.style.opacity = 0;\n  setTimeout(function () {\n    modal.style.display = 'none';\n    overlay.style.display = 'none';\n  }, 500);\n};\n\nvar open = function open() {\n  document.body.style.overflow = 'hidden';\n  modal.style.display = 'block';\n  overlay.style.display = 'block';\n  setTimeout(function () {\n    modal.style.opacity = 1;\n    overlay.style.opacity = 1;\n  }, 100);\n};\n\nvar closeBtn = document.querySelector('.modal__close');\nvar openBtn = document.querySelector('.about__right button');\nvar openResume = document.querySelector('.aspirant-info__summary');\noverlay.addEventListener('click', close);\ncloseBtn.addEventListener('click', close);\nopenBtn ? openBtn.addEventListener('click', open) : null;\nopenResume ? openResume.addEventListener('click', open) : null;\n\n//# sourceURL=webpack:///./src/js/modal.js?")}});
//# sourceMappingURL=aspirant.js.map
