!function(r){var e={};function n(t){if(e[t])return e[t].exports;var o=e[t]={i:t,l:!1,exports:{}};return r[t].call(o.exports,o,o.exports,n),o.l=!0,o.exports}n.m=r,n.c=e,n.d=function(r,e,t){n.o(r,e)||Object.defineProperty(r,e,{enumerable:!0,get:t})},n.r=function(r){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(r,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(r,"__esModule",{value:!0})},n.t=function(r,e){if(1&e&&(r=n(r)),8&e)return r;if(4&e&&"object"==typeof r&&r&&r.__esModule)return r;var t=Object.create(null);if(n.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:r}),2&e&&"string"!=typeof r)for(var o in r)n.d(t,o,function(e){return r[e]}.bind(null,o));return t},n.n=function(r){var e=r&&r.__esModule?function(){return r.default}:function(){return r};return n.d(e,"a",e),e},n.o=function(r,e){return Object.prototype.hasOwnProperty.call(r,e)},n.p="",n(n.s="./src/js/event.js")}({"./src/js/burger.js":
/*!**************************!*\
  !*** ./src/js/burger.js ***!
  \**************************/
/*! no static exports found */function(module,exports){eval("function _toConsumableArray(arr) { return _arrayWithoutHoles(arr) || _iterableToArray(arr) || _unsupportedIterableToArray(arr) || _nonIterableSpread(); }\n\nfunction _nonIterableSpread() { throw new TypeError(\"Invalid attempt to spread non-iterable instance.\\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.\"); }\n\nfunction _unsupportedIterableToArray(o, minLen) { if (!o) return; if (typeof o === \"string\") return _arrayLikeToArray(o, minLen); var n = Object.prototype.toString.call(o).slice(8, -1); if (n === \"Object\" && o.constructor) n = o.constructor.name; if (n === \"Map\" || n === \"Set\") return Array.from(o); if (n === \"Arguments\" || /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n)) return _arrayLikeToArray(o, minLen); }\n\nfunction _iterableToArray(iter) { if (typeof Symbol !== \"undefined\" && Symbol.iterator in Object(iter)) return Array.from(iter); }\n\nfunction _arrayWithoutHoles(arr) { if (Array.isArray(arr)) return _arrayLikeToArray(arr); }\n\nfunction _arrayLikeToArray(arr, len) { if (len == null || len > arr.length) len = arr.length; for (var i = 0, arr2 = new Array(len); i < len; i++) { arr2[i] = arr[i]; } return arr2; }\n\nvar burgerHandler = function burgerHandler(dropdown, event) {\n  var parent = event.target.classList.contains('burger') ? event.target : event.target.parentElement;\n\n  var spans = _toConsumableArray(parent.children);\n\n  if (!parent.classList.contains('active')) {\n    parent.classList.toggle('active');\n    dropdown.style.transform = 'translateY(0)';\n    document.body.style.overflowY = 'hidden';\n    spans.map(function (e) {\n      e.style.backgroundColor = 'white';\n    });\n    parent.style.borderColor = 'white';\n    spans[0].style.top = '50%';\n    spans[2].style.top = '50%';\n    setTimeout(function () {\n      spans[0].style.transform = 'rotate(45deg)';\n      spans[1].style.opacity = 0;\n      spans[2].style.transform = 'rotate(-45deg)';\n    }, 500);\n  } else {\n    parent.classList.toggle('active');\n    dropdown.style.transform = 'translateY(-250%)';\n    document.body.style.overflowY = 'unset';\n    spans.map(function (e) {\n      return e.style.backgroundColor = '#D40F14';\n    });\n    parent.style.borderColor = '#D40F14';\n    spans[0].style.transform = 'rotate(0deg)';\n    spans[1].style.opacity = 1;\n    spans[2].style.transform = 'rotate(0deg)';\n    setTimeout(function () {\n      spans[0].style.top = 'calc(50% - 7px)';\n      spans[2].style.top = 'calc(50% + 7px)';\n      spans[0].style.transform = 'translate3d(0, -50%, 0)';\n      spans[2].style.transform = 'translate3d(0, -50%, 0)';\n    }, 500);\n  }\n};\n\nvar burger = document.querySelector('.burger');\nvar dropdown = document.querySelector('.dropdown');\nburger.addEventListener('click', burgerHandler.bind(this, dropdown));\n\n//# sourceURL=webpack:///./src/js/burger.js?")},"./src/js/event.js":
/*!*************************!*\
  !*** ./src/js/event.js ***!
  \*************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _burger__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./burger */ "./src/js/burger.js");\n/* harmony import */ var _burger__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(_burger__WEBPACK_IMPORTED_MODULE_0__);\n\n\n//# sourceURL=webpack:///./src/js/event.js?')}});
//# sourceMappingURL=event.js.map
